# Generated by Django 4.2.30 on 2026-09-05 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Application Created'), ('SUBMITTED', 'Application Submitted'), ('DOC_UPLOADED', 'Document Uploaded'), ('DOC_REPLACED', 'Document Replaced'), ('DOC_APPROVED', 'Document Approved'), ('DOC_REJECTED', 'Document Rejected'), ('CORRECTION_REQUESTED', 'Correction Requested'), ('PENDING_APPROVAL', 'Moved to Pending Approval'), ('FINAL_APPROVED', 'Final Application Approved'), ('FINAL_REJECTED', 'Final Application Rejected'), ('COMMENT_ADDED', 'Comment Added')], max_length=40)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_triggered', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='onboarding.onboardingapplication')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
