# Generated by Django 4.2.30 on 2026-09-05 05:10

import apps.documents.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='partner_documents/', validators=[apps.documents.models.validate_file_extension_and_size])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('NOT_UPLOADED', 'Not Uploaded'), ('UPLOADED', 'Uploaded'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='UPLOADED', max_length=30)),
                ('reviewer_comment', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.onboardingapplication')),
                ('checklist_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='onboarding.applicationchecklistitem')),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicationDocument',
        ),
    ]
